name: Deploy to Glitch
on:
  push:
    branches:
      - master
jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy To Glitch
      uses: kanadgupta/glitch-sync@master
      with:
        project-id: '${{ secrets.PROJECT_ID }}'
        auth-token: '${{ secrets.AUTH_TOKEN }}'
